app = "jungle-champ-select"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[build.args]
  VITE_API_URL = "https://jungle-champ-select.fly.dev"
  VITE_SOCKET_URL = "https://jungle-champ-select.fly.dev"

[env]
  NODE_ENV = "production"
  DATABASE_PATH = "/data/polls.sqlite"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0

[[mounts]]
  source = "polls_data"
  destination = "/data"

